from typing import Union


class Size:
    def __init__(self, value: Union[int, str]): ...

    @property
    def is_auto(self) -> bool: ...
    @property
    def is_star(self) -> bool: ...
    @property
    def value(self) -> int: ...
