def distance(*pairs: tuple[int, int]) -> float: ...
def hsl_to_rgb(h: int, s: float, l: float) -> tuple[int, int, int]: ...
def hsv_to_rgb(h: int, s: float, l: float) -> tuple[int, int, int]: ...
def rgb_to_hsl(r: int, g: int, b: int) -> tuple[int, float, float]: ...
def rgb_to_hsv(r: int, g: int, b: int) -> tuple[int, float, float]: ...
def interpolate(v1: float, v2: float, p: float) -> float: ...
