def decimal_to_latin(d: int) -> str: ...
def decimal_to_roman(d: int) -> str: ...
def height(s: str) -> int: ...
def len(s: str) -> int: ...
def normalize(s: str) -> str: ...
def width(s: str) -> int: ...
